// src/types/ink-engine.d.ts
// This declares the global function that Emscripten's MODULARIZE option makes available
// and the shape of the module object itself.

interface EmscriptenModule {
    _malloc: (size: number) => number;
    _free: (ptr: number) => void;
    HEAPU8: Uint8Array;
    // Add other Emscripten-specific properties you might use
    ccall: (ident: string, returnType: string | null, argTypes: string[], args: any[]) => any;
    cwrap: (ident: string, returnType: string | null, argTypes: string[]) => (...args: any[]) => any;
    onRuntimeInitialized: () => void;
    FS: any; // File system access, if needed
    // ... other Emscripten properties
}

interface EmscriptenVector<T> {
    push_back(value: T): void;
    get(index: number): T;
    size(): number;
    delete(): void;
}

// Emscripten-generated Point object (from emscripten::value_object)
interface WasmPoint {
    x: number;
    y: number;
    pressure: number;
}

// The module object generated by Emscripten
interface InkEngineModule extends EmscriptenModule {
    VectorPoint: new () => EmscriptenVector<WasmPoint>; // Constructor for Emscripten.Vector<WasmPoint>
    // The C++ function 'process_stroke' bound using EMSCRIPTEN_BINDINGS
    process_stroke: (rawPoints: EmscriptenVector<WasmPoint>) => EmscriptenVector<WasmPoint>;
}

// Declare the factory function that the Emscripten-generated JS module exports
declare module "ink-engine" {
    const InkEngineFactory: (options?: { locateFile?: (path: string) => string }) => Promise<InkEngineModule>;
    export default InkEngineFactory;
}
